DJWOMS/GSpot

.github/workflows/frontend_dev.yml, .github/workflows/frontend_prod.yml, frontend/README.md
=> Added environments for frontend

backend/games/.flake8, backend/games/.pre-commit-config.yaml, backend/games/requirements.txt
if developer try to commit code which does not fit pep8, then the commit will be a canceled
=> games | Configuring Pre-Commit and Linting

backend/games/base/paginations.py, backend/games/config/settings.py, backend/games/core/views.py
=> Games | Pagination

backend/channels/docker-compose.yml
Fixed problems with long starting RabbitMQ. Added some checks to define that service is started.
=> CHANNELS | hotfix rabbitmq

backend/payments/Dockerfile, backend/payments/README.md, backend/payments/config/settings.py, backend/payments/docker-compose.yml, backend/payments/entrypoint.sh, backend/payments/start.sh
change Dockerfile to multistage build
soft fix docker-compose
edit a little README
=> Payments | multistage build slim

backend/games/config/urls.py, backend/games/core/serializers.py, backend/games/reference/serializers.py, backend/games/utils/serializers.py, backend/games/utils/urls.py, backend/games/utils/views.py
* Жанры
* Под-жанры
* Платформы
* Минимальная максимальная цена
=> Games | Endpoint to get filters for frontend

frontend/components/Header/Header.tsx, frontend/configs/index.ts, frontend/package-lock.json, frontend/package.json
updated to next 13.3 and small fix for build
=> Frontend | Fixed build for localhost and 127.0.0.1

backend/users/backend/config/urls.py, backend/users/backend/developers/permissions.py, backend/users/backend/developers/serializers.py, backend/users/backend/developers/tests/test_models.py, backend/users/backend/developers/tests/test_serializers.py, backend/users/backend/developers/tests/test_views.py, backend/users/backend/developers/urls.py, backend/users/backend/developers/views.py
=> users | add developers views

backend/channels/.gitignore, backend/channels/chat/core/models.py, backend/channels/chat/main.py, backend/channels/chat/requirements.txt, backend/channels/chat/src/messages/models.py, backend/channels/chat/src/notifications/models.py, backend/channels/chat/src/rooms/models.py, backend/channels/chat/src/router.py, backend/channels/chat/src/users/models.py, backend/channels/requirements.txt
=> Channels | Added websocket action model

backend/channels/.gitignore, backend/channels/.pre-commit-config.yaml, backend/channels/broker/Dockerfile, backend/channels/broker/consumers/abstract.py, backend/channels/broker/publisher.py, backend/channels/chat/Dockerfile, backend/channels/chat/requirements.txt, backend/channels/docker-compose.yml, backend/channels/pyproject.toml
added linters and pre-commit, fixed some docker errors
=> Channels | added linters and pre-commit, fixed some docker errors

frontend/components/Alert/Alert.module.scss, frontend/components/Alert/Alert.tsx
Подготовила компонент Alert. Но не знаю как регулировать, если нам нужно несколько разных алертов одновременно отображать, где в таком случае хранить стейт со всеми алертами
=> Frontend | alert

frontend/components/Alert/Alert.module.scss, frontend/components/Alert/Alert.tsx
удалила излишний стиль для hidden, компонент рендерится по условию {open ? 'visible'  :  null}
=> Feature | alert (changes)

backend/users/backend/base/validators.py
=> Users | Permission Hotfix

backend/payments/apps/external_payments/services/check_yookassa_response.py, backend/payments/apps/external_payments/views.py
Create function check_yookassa_respone, that before payment process check that response from yookassa.
=> Payments | Check yookassa response

backend/games/finance/serializers.py, backend/games/finance/urls.py, backend/games/finance/views.py
=> Games | Library endpoint

frontend/app/(main)/catalog/page.tsx, frontend/app/(main)/profile/favorites/page.tsx, frontend/components/Pagination/Pagination.module.css, frontend/components/Pagination/Pagination.tsx
Добавила собственную реализацию пагинации (как серверного компонента). В компонент пагинации передаются пропсы path, currentPage, query (вариативно). Стили перенесла из предыдущей реализации, только стрелки задизейблила на крайних страницах и убрала лишний отступ у выбранной страницы.
Библиотеку react-paginate из зависимостей не удаляла.
=> Frontend | Feature/refactoring pagination

frontend/app/(main)/profile/settings/@password/page.tsx, frontend/app/(main)/profile/settings/@profile/ProfileForm.tsx, frontend/app/(main)/profile/settings/page.module.css, frontend/components/Form/Form.module.css, frontend/components/Form/Form.tsx
=> Frontend | Filled a reusable form with data

backend/games/core/serializers.py, backend/games/core/urls.py, backend/games/finance/serializers.py
Если отправить несуществующий жанр или язык то вернется 400 статус с сообщением
```
[
"Language matching query does not exist."
]
or
[
"Genre matching query does not exist."
]
```
=> Games | handle errors

backend/payments/apps/payment_accounts/views.py
=> Payments | Delete else

frontend/app/mocks/profile/[id]/route.ts, frontend/features/profile/mocks/index.ts, frontend/features/profile/types/index.ts
Посмотри, пожалуйста, верно ли я вообще сделала. Пока без игр, только  инфа пользователя.
=> Frontend | add mocks route UserPublicPage

frontend/app/(main)/page.tsx, frontend/lib/errorHandler.ts, frontend/lib/fetchServerSide.ts, frontend/package-lock.json, frontend/package.json
Добавил функцию которая отображает ошибки 401 и 400 на экран
Для отображения ошибки добавил зависимость react-hot-toast
=> FRONTEND | handling errors

frontend/app/(auth)/signin/page.module.css, frontend/app/(auth)/signin/page.tsx, frontend/app/(main)/layout.tsx, frontend/components/Header/Header.tsx
Использован универсальный компонент Form в SignIn, добавлен свой page.module.css. Добавлена проверка на авторизацию в header. Моковый роут за инф-цией о профиле не реализован в header (возьму следующей задачей).
=> Frontend | auth refactor

backend/users/backend/administrator/admin.py, backend/users/backend/common/admin.py, backend/users/backend/customer/admin.py, backend/users/backend/developer/admin.py, backend/users/backend/developer/models.py
* Обрати внимание на изменение в модели компании, директории разарботчика. Была ошибка загрузки шаблона
=> Users | Create admin panel 

backend/games/finance/views.py
Little fix offer view for show schema in swagger
=> Games | Fix offer body Swagger

backend/games/.pre-commit-config.yaml, backend/games/pyproject.toml
Add black, isort and flake8 into pre-commit
Max length = 100 symbols
=> Games | Added black,  isort, flake into pre-commit
